name = "Polymake"
uuid = "d720cf60-89b5-51f5-aff5-213f193123e7"
repo = "https://github.com/oscar-system/Polymake.jl.git"
version = "0.11.9"

[deps]
BinaryWrappers = "f01c122e-0ea1-4f85-ad8f-907073ad7a9f"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Mongoc = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"
Ninja_jll = "76642167-d241-5cee-8c94-7a494e8cb7b7"
Perl_jll = "83958c19-0796-5285-893e-a1267f8ec499"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOPCOM_jll = "36f60fef-b880-50dc-9289-4aaecee93cc3"
lib4ti2_jll = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
libpolymake_julia_jll = "4d8266f6-2b3b-57e3-ad7a-d431eaaac945"
polymake_jll = "7c209550-9012-526c-9264-55ba7a78ba2c"
polymake_oscarnumber_jll = "10f31823-b687-53e6-9f29-edb9d4da9f9f"

[compat]
BinaryWrappers = "~0.1.0"
CxxWrap = "~0.14"
JSON = "^0.20, ^0.21"
Libdl = "^1.6"
Mongoc = "~0.6.0, ~0.7.0, ~0.8.0, ~0.9.0"
Ninja_jll = "^1.11.1"
Perl_jll = "^5.34.0"
Pkg = "^1.6"
REPL = "^1.6"
Scratch = "^1.1"
SparseArrays = "^1.6"
TOPCOM_jll = "~0.17.8"
julia = "^1.6"
lib4ti2_jll = "^1.6.10"
libpolymake_julia_jll = "~0.11.1"
polymake_jll = "^400.1100.1"
polymake_oscarnumber_jll = "~0.2.7"
